config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/search', to: "pages#search", as: :search
  get '/dashboard', to:"pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :masks do
    resources :bookings, only: [:index, :new, :create]
  end
    resources :bookings, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :mask
  validates :start_date, :end_date, presence: :true, availability: true
end

app/models/mask.rb
CATEGORIES = ['bear', 'cat', 'dog', 'horse', 'mouse', 'rabbit', 'pig', 'gas']
class Mask < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: :true
  validates :price, presence: :true
  validates :photo, attached: true
  validates :category, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :masks
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mask, only: [:new, :create]

  def index
     @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new

  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.mask = @mask
    @booking.user = current_user
    # It has to be this way because of the way flatpicker works with the dates"
    # @booking.start_date = params[:booking][:start_date].split("to")[0].strip
    # @booking.end_date = params[:booking][:start_date].split("to")[1].strip
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

private

  def set_mask
    @mask = Mask.find(params[:mask_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/masks_controller.rb
class MasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    if params[:search].present?
      sql_query = "name ILIKE :query
      OR description ILIKE :query
      OR category ILIKE :query
      OR address ILIKE :query
      "
      @masks = Mask.where(sql_query, query: "%#{params[:search][:query]}%")
    else
      @masks = Mask.all
    end
    geocode(@masks)
  end

  def show
    @mask = Mask.find(params[:id])
  end

  def new
    @mask = Mask.new
  end

  def create
    @mask = Mask.new(mask_params)
    @mask.user = current_user
    if @mask.save
      redirect_to mask_path(@mask)
    else
      render :new
    end
  end

  def edit
    @mask = Mask.find(params[:id])
  end

  def update
    @mask = Mask.find(params[:id])
    @mask.update(mask_params)
    redirect_to mask_path(@mask)
  end

  def destroy
    @mask = Mask.find(params[:id])
    @mask.destroy
    redirect_to dashboard_path
  end

  private
  def mask_params
    params.require(:mask).permit(:name, :description, :category, :price, :photo, :address)
  end

  def geocode(masks)
    masks.geocoded #returns mask with coordinates

    @markers = masks.map do |mask|
      {
        lat: mask.latitude,
        lng: mask.longitude
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :home, :search]
  def dashboard
    @user = current_user
    @bookings = @user.bookings
  end
  def home
  end
  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@mask, @booking] do |f| %>
  <%= f.input :start_date, as: :string, wrapper_html: { class: "inline_field_wrapper" }, label: "From"%>
  <%= f.input :end_date, as: :string, wrapper_html: { class: "inline_field_wrapper" }, label: "To", disabled: true%>
  <%= f.submit class: "submit-button" %>
<% end %>

app/views/bookings/index.html.erb
<h1>Here the bookings</h1>

app/views/bookings/new.html.erb
<div class= "container-mask">
  <div class="form-container">
    <%= render "form" %>
    <div class="widget-content" data-unavailable="<%= @mask.unavailable_dates.to_json %>"></div>
    <div class="back-to-index">
        <%= link_to 'Back to mask', mask_path(@mask), class: "button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>intiMASKy</title>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="icon" type="image/svg" href="https://res.cloudinary.com/dhkoueugk/image/upload/v1612988830/icon_bfk2z3.svg" sizes="32x32" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= stylesheet_pack_tag 'application'%> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

<body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>

</html>

app/views/masks/_form.html.erb
<%= simple_form_for @mask do |f|%>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price, label: 'Price per day' %>
  <%= f.input :address %>
  <%= f.input :category, collection: CATEGORIES %>
  <%= f.input :photo, as: :file %>
  <div class="button-add">
  <%= f.submit :class => "submit-button"%>
  </div>
<% end %>

app/views/masks/edit.html.erb
<div class="container-mask m-15">
  <div class="form-container">
  <h2 class="pt-15">Edit the mask:</h2>
    <%= render 'form' %>
    <div class="show-buttons">
      <%= link_to 'Go back', mask_path(@mask), class: "button weird-button" %>
      <%= link_to 'See all masks', masks_path, class: "button weird-button"  %>
    </div>
  </div>
</div>

app/views/masks/index.html.erb
<div class="index-container-main">
    <div class="container-mask" id="index-container-mask">
        <section class="card-index">
            <h1>What do you desire?</h1>
            <% if @masks %>
            <div class="featured-cards">
                <% @masks.shuffle.each do |mask| %>
                <div class="card-product">
                    <div class="border-card">
                        <div class="card__image-container">
                            <%= cl_image_tag mask.photo.key%>
                        </div>
                    </div>
                    <div class="card__content">
                        <h5>
                            <%= link_to(mask.name, mask_path(mask)) %>
                            </h3>
                            <h6>
                                <%= mask.description %>
                        </h5>
                        <p>€
                            <%= mask.price %> per day</p>
                    </div>
                </div>
                <% end %>
            </div>
            <% end %>
            <a class="button" href="/search">Search again</a>
        </section>
        <section class="map-index">
            <div id="map" style="width: 30vw; min-height: 90vh;
  height: 90vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </section>
    </div>
</div>
<!-- if statement because of Heroku -->

app/views/masks/new.html.erb
<div class="container-mask m-15">
  <div class="add-form">
  <h2 class="pt-15">Add a mask:</h2>
    <%= render 'form' %>
    <div class="back-index-button">
      <%= link_to 'See all masks', masks_path, class: "button" %>
    </div>
  </div>
</div>

app/views/masks/show.html.erb
<div class="show-main-container">
    <div class="show-card-product">
      <div class="border-card">
        <div class="show-card__image-container">
            <%= cl_image_tag @mask.photo.key%>
        </div>
        <div class="card__content">
          <h2 id='mask-name'>
              <%= link_to(@mask.name, mask_path(@mask)) %>
          </h2>
          <h6 id="mask-description">
                  <%= @mask.description %>
          </h6>
          <p id='mask-price'>€
              <%= @mask.price %> per day
          </p>
        </div>
        <div id="mask-category">
          <p>
            Category: <%= @mask.category %>
          </p>
        </div>
        <div id='show-book-button'>
          <%= link_to 'Book', new_mask_booking_path(@mask), class:"weird-book submit-button", id:"book-button" %>
        </div>
      </div>
    </div>
    <div class="show-buttons">
      <ul class="action-list p-10">
        <li><%= link_to 'Back to Masks', masks_path, class:"weird-button button" %></li>
      </ul>
    </div>

</div>

app/views/pages/dashboard.html.erb
<div class="container-mask pt-5">
  <h1 class="">Your Bookings</h1>
  <% if @bookings %>
      <div class="featured-masks">
        <% @bookings.each do |booking| %>
          <div class="card-product">
            <div class="border-card">
              <div class="card__image-container">
                <%= cl_image_tag booking.mask.photo.key%>
              </div>
            </div>
            <div class="card__content">
              <h5><%= link_to(booking.mask.name, mask_path(booking.mask)) %></h3>
              <h6>From <%= booking.start_date %></h6>
              <h6>To <%= booking.end_date %></h6>
              <p>€<%= booking.mask.price%> per day</p>
              <%= link_to "Cancel", booking_path(booking),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "submit-button" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  <div class="uploaded-masks pt-5">
    <h1>Your Mask Posts</h1>
    <% if @user.masks %>
      <div class="featured-masks">
        <% @user.masks.each do |mask| %>
          <div class="card-product">
            <div class="border-card">
              <div class="card__image-container">
              <%= cl_image_tag mask.photo.key%>
              </div>
            </div>

            <div class="card__content">
              <h5><%= link_to(mask.name, mask_path(mask)) %></h5>
              <h6><%= mask.description %></h6>
              <p>€<%= mask.price%> per day</p>
              <%= link_to "Edit", edit_mask_path(mask), class: "submit-button",
                  method: :get %>
              <%= link_to "Remove", mask_path(mask.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "submit-button" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class='main-container'>
    <div class="home-banner">
        <p class="typescript">
            <span id="banner-typed-text"></span>
        </p>
        <div class="landing-page-row">
            <div class="find-a-mask">
            <%= link_to 'Find A Mask', '/search', class:"button-landing-page"%>
            </div>
            <div class="post-your-mask">
            <%= link_to 'Post Your Mask', '/masks/new', class:"button-landing-page"%>
            </div>
        </div>
    </div>
    <%= render "shared/content_options" %>
</div>

app/views/pages/search.html.erb
<div class="container-mask text-center">
    <div class="" id="search">
        <section class="search-header d-flex flex-column">
            <h1>What type of mask are you looking for?</h1>
            <div class="text-center search-form">
              <%= simple_form_for :search, method: :get, url: masks_path do |f| %>
                <%= f.input :query, label: false, placeholder: "Search", input_html: { class: "text-center search-bar"} %>
                <%= f.submit 'Submit', class: "submit-button" %>
              <% end %>
            </div>
        </section>
      </div>
        <hr>
<h2 class="text-center pb-5">Featured Masks</h2>
            <div class="featured-masks">
              <% masks = Mask.all %>
              <% selected_masks = masks.sample(4) %>
              <% selected_masks.each do |mask| %>
                <div class="card-product">
                  <div class="border-card">
                    <div class="card__image-container">
                    <%= cl_image_tag mask.photo.key%>
                    </div>
                  </div>

                  <div class="card__content">
                    <h5><%= link_to(mask.name, mask_path(mask)) %></h3>
                    <h6><%= mask.description %></h5>
                    <p>€<%= mask.price%> per day</p>
                  </div>
                </div>
              <% end %>
            </div>
    </div>
</div>

app/views/shared/_content_options.html.erb
<!-- <div class="content_options">
    <div class="container landing-page">
        <div class="cards d-flex justify-content-around row">
            <div class="card border-0">
                <div class="card-body rounded-lg" id="leftcard">
                    <h2 class="card-title">Find Mask</h2>
                    <div class="bottom-text">
                        <div class="button-5" id="button-5">
                            <div id="translate"></div>
                            <a href="#"><strong>
                                    <%= link_to 'Find', '/search' %>
                                </strong></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card border-0">
                <div class="card-body rounded-lg" id="rightcard">
                    <h2 class="card-title">Post Mask</h2>
                    <div class="bottom-text">
                        <div class="button-5" id="button-5">
                            <div id="translate"></div>
                            <a href="#"><strong>
                                    <%= link_to 'Post', '' %>
                                </strong></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div></div>

 -->

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-center align-items-center">
  <a href="#"><i class="fab fa-facebook"></i></a>
  <a href="#"><i class="fab fa-twitter"></i></a>
  <a href="#"><i class="fab fa-instagram"></i></a>
  <a href="#"><i class="fab fa-youtube"></i></a>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <% if current_page?(root_path) %>
      <i class='bx bx-mask bx-tada' ></i>
    <% else %>
      <i class='bx bx-mask bx-tada crimsom' ></i>
    <% end %>
    <%# <%= image_tag "https://res.cloudinary.com/dqlvehu5z/image/upload/o_39/v1582558617/mask_lolhmn.png" %>
    
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class='bx bx-menu bx-rotate-180' style='color:#ffffff'  ></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to root_path, class: 'nav-link' do %>
          <span>Home</span>
          <% end %>
        </li>

        <li class="nav-item active">
          <%= link_to "Search", search_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Masks", "/masks", class: "nav-link" %>
        </li>
        <li class="nav-item active">

          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">

          <%= image_tag "https://randomuser.me/api/portraits/men/76.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false =%>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View my bookings", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Post a mask ", new_mask_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item grow">
          <% if current_page?(root_path) %>
            <%= link_to "Login", new_user_session_path, class: "nav-link-login" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link-login-crimsom" %>
          <% end %>
          
          </li>
        <% end %>
    </ul>
  </div>
</div>